"""
Test sentences for evaluating WSD models.
20 sentences per sense for each word.
"""

TEST_SENTENCES = {
    "director": {
        1: [
            "The board of directors appointed a new executive director to lead the company.",
            "As the marketing director, she oversees all advertising campaigns and brand strategy.",
            "The hospital director announced new patient care initiatives this morning.",
            "Our regional director will visit the branch office next week to review operations.",
            "The director of human resources implemented a new employee wellness program.",
            "She was promoted to director of sales after five years of outstanding performance.",
            "The school director met with parents to discuss curriculum changes.",
            "The director of operations streamlined the supply chain to reduce costs.",
            "He serves as the director of the nonprofit organization's fundraising efforts.",
            "The museum director curated a special exhibition featuring contemporary artists.",
            "The finance director presented the quarterly earnings report to the shareholders.",
            "The technical director oversees all IT infrastructure and software development projects.",
            "As program director, he coordinates multiple initiatives across different departments.",
            "The director of communications manages all public relations and media outreach efforts.",
            "She was named director of the research division after publishing groundbreaking studies.",
            "The director of security implemented new protocols following the recent incident.",
            "The board selected a new director to replace the retiring chief executive officer.",
            "The director of customer service improved response times by 40% this quarter.",
            "Our director has been with the organization for over 20 years and knows every process.",
        ],
        2: [
            "The director shouted 'cut' after the actor flubbed his lines for the third time.",
            "Award-winning director Christopher Nolan is known for his complex narrative structures.",
            "The theater director blocked the opening scene during yesterday's rehearsal.",
            "She aspires to become a film director and has already made two short movies.",
            "The director's vision transformed the classic play into a modern masterpiece.",
            "After the screening, the director answered questions about the film's symbolism.",
            "The documentary director spent three years filming wildlife in the Arctic.",
            "The director worked closely with the cinematographer to achieve the perfect lighting.",
            "Critics praised the director for her innovative approach to storytelling.",
            "The director's cut of the movie includes an additional 30 minutes of footage.",
            "The director chose to shoot the entire film in black and white for artistic effect.",
            "Independent directors often struggle to secure funding for their first feature films.",
            "The director collaborated with the screenwriter to refine the dialogue in several key scenes.",
            "Many aspiring directors study at film schools to learn the craft of visual storytelling.",
            "The director received a standing ovation at the film festival premiere last night.",
            "The director's previous work influenced her approach to directing this psychological thriller.",
            "The director spent months in pre-production planning every shot and camera angle.",
            "The director's unique style has earned her recognition as one of the industry's rising talents.",
            "The director wrapped principal photography after three months of intensive shooting.",
        ],
    },
    "overtime": {
        1: [
            "Factory workers are required to work overtime during peak production seasons.",
            "The new labor law mandates double pay for overtime hours worked on holidays.",
            "Many employees complain about mandatory overtime affecting their work-life balance.",
            "The company policy limits overtime to 15 hours per week per employee.",
            "She earned extra money by working overtime shifts at the hospital.",
            "The union negotiated better overtime compensation rates in the new contract.",
            "Overtime work has increased significantly since the project deadline was moved up.",
            "The manager approved overtime for the team to complete the urgent client request.",
            "Some workers prefer overtime because it significantly boosts their monthly income.",
            "The HR department tracks all overtime hours to ensure compliance with regulations.",
            "Employees must submit overtime requests at least 48 hours in advance for approval.",
            "The accounting department calculated overtime pay for all hourly workers last month.",
            "Working excessive overtime can lead to employee burnout and decreased productivity.",
            "The supervisor authorized emergency overtime when the server crashed on Friday night.",
            "The new scheduling system automatically flags when employees approach their overtime limit.",
            "Overtime rates vary depending on whether the work is performed on weekdays or weekends.",
            "The company offers compensatory time off as an alternative to overtime pay.",
            "The labor union filed a grievance over unpaid overtime hours from the previous quarter.",
            "The project manager requested overtime authorization to meet the client's tight deadline.",
        ],
        2: [
            "The basketball game went into triple overtime before a winner was determined.",
            "They scored the winning touchdown in the final seconds of overtime.",
            "The hockey match ended in a tie after regulation and two overtime periods.",
            "Fans were on the edge of their seats during the intense overtime period.",
            "The team's strategy changed dramatically once the game entered overtime.",
            "She made a crucial save in overtime that kept her team's championship hopes alive.",
            "The referee's controversial call in overtime sparked heated debate among analysts.",
            "Both teams were exhausted by the time the game reached its second overtime.",
            "The overtime rules in this league differ from standard professional regulations.",
            "He scored a hat trick in overtime, leading his team to an unexpected victory.",
            "The soccer match remained tied after 90 minutes, forcing the game into overtime.",
            "In college basketball, overtime periods last five minutes instead of the standard four.",
            "The goalie's spectacular save in overtime prevented the opposing team from winning.",
            "The coach called a timeout to strategize before the start of the first overtime period.",
            "The crowd erupted when the home team scored the game-winning goal in sudden-death overtime.",
            "The overtime period began with both teams showing signs of fatigue from the long match.",
            "The referee's decision to extend the game into overtime was met with mixed reactions.",
            "The player's overtime performance earned him the Most Valuable Player award.",
            "The championship game required four overtime periods before a winner was finally determined.",
        ],
    },
    "rubbish": {
        1: [
            "The city council introduced new bins to encourage proper rubbish disposal.",
            "Please separate your recyclables from general rubbish before collection day.",
            "The beach cleanup volunteers filled dozens of bags with plastic rubbish.",
            "Illegal dumping of construction rubbish has become a problem in this neighborhood.",
            "The rubbish truck comes every Tuesday morning to collect household waste.",
            "She sorted through the rubbish to find items that could be recycled.",
            "The landfill is nearly full and cannot accept more rubbish this month.",
            "Composting organic rubbish helps reduce the amount of waste sent to landfills.",
            "The rubbish heap behind the building attracted rats and other pests.",
            "Residents are required to place their rubbish bins at the curb by 6 AM.",
            "The municipal waste management department handles all rubbish collection in the city.",
            "The overflowing rubbish container attracted seagulls and created an unpleasant odor.",
            "The environmental group organized a campaign to reduce single-use plastic rubbish.",
            "The construction site generated tons of building rubbish that needed proper disposal.",
            "The rubbish sorting facility processes over 500 tons of waste material daily.",
            "The city implemented a new program to convert organic rubbish into compost.",
            "The rubbish collection schedule was disrupted due to the holiday weekend.",
            "The abandoned lot was filled with old furniture and other household rubbish.",
            "The waste management company charges extra fees for oversized rubbish items.",
        ],
        2: [
            "That article is complete rubbish and contains numerous factual errors.",
            "Don't listen to that rubbish about the conspiracy theory; it's completely unfounded.",
            "The politician dismissed the accusations as baseless rubbish from his opponents.",
            "She told him to stop talking rubbish and focus on the real issues.",
            "The reviewer called the novel pretentious rubbish that wasted the reader's time.",
            "That's absolute rubbish and you know it; the evidence doesn't support your claim.",
            "The professor dismissed the student's argument as intellectual rubbish.",
            "He's been spreading that same rubbish for years without any proof.",
            "The editorial was nothing but inflammatory rubbish designed to provoke controversy.",
            "I'm tired of hearing that same old rubbish repeated over and over again.",
            "The scientific community dismissed the paper as methodological rubbish with flawed data.",
            "That's a load of rubbish and I won't waste my time arguing about it anymore.",
            "The journalist's article was nothing but sensationalist rubbish designed to generate clicks.",
            "The teacher told the student that his excuse was complete rubbish and unacceptable.",
            "The online comments section was filled with hateful rubbish from anonymous trolls.",
            "The expert panel concluded that the study's findings were statistical rubbish.",
            "The politician's speech was full of the same old rubbish we've heard before.",
            "The book review described the author's latest work as derivative rubbish lacking originality.",
            "The judge dismissed the defendant's testimony as self-serving rubbish without merit.",
        ],
    },
}

